# ServiceAccount pour le backend
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-service-account
  namespace: default
---
# ServiceAccount pour le frontend
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-service-account
  namespace: default
---
# Role avec permissions limitées pour le backend
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backend-role
  namespace: default
rules:
  # Peut lire les secrets (pour la config DB)
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["postgres-secret"]
    verbs: ["get"]
  # Peut lire les configmaps
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
  # Peut lire les services (pour service discovery)
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]
---
# Role avec permissions minimales pour le frontend
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: frontend-role
  namespace: default
rules:
  # Frontend n'a besoin que de lire les configmaps
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
---
# Lier le Role au ServiceAccount backend
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: backend-service-account
    namespace: default
roleRef:
  kind: Role
  name: backend-role
  apiGroup: rbac.authorization.k8s.io
---
# Lier le Role au ServiceAccount frontend
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: frontend-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: frontend-service-account
    namespace: default
roleRef:
  kind: Role
  name: frontend-role
  apiGroup: rbac.authorization.k8s.io
